# Generated by Django 3.2.12 on 2022-03-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20220324_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelsquestion',
            name='id_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.label'),
        ),
        migrations.AlterField(
            model_name='labelsquestion',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
