# Generated by Django 3.2.12 on 2022-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20220325_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'UNSOLVED'), (3, 'SOLVED'), (4, 'CLOSED')], default=1, max_length=30),
        ),
    ]
