# Generated by Django 3.2.12 on 2022-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[(1, 'NEW'), (2, 'UNSOLVED'), (3, 'SOLVED'), (4, 'CLOSED')], default=1, max_length=15),
        ),
    ]
