# Generated by Django 3.2.12 on 2022-04-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'UNSOLVED'), (3, 'SOLVED'), (4, 'CLOSED')], default=1),
        ),
    ]
