# Generated by Django 3.2.12 on 2022-04-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0004_auto_20220325_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id_answer', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('description', models.TextField()),
                ('votes', models.IntegerField()),
                ('is_solution', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=255)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
    ]
